/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fihtdc_grideye_MainActivity */

#ifndef _Included_com_fihtdc_grideye_MainActivity
#define _Included_com_fihtdc_grideye_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fihtdc_grideye_MainActivity
 * Method:    getMsgFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fihtdc_grideye_MainActivity_getMsgFromJni
  (JNIEnv *, jobject);

/*
 * Class:     com_fihtdc_grideye_MainActivity
 * Method:    getStatusFromJni
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_fihtdc_grideye_MainActivity_getStatusFromJni
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL
Java_com_evenwell_grideye_MainActivity_sendByteArrayToJNI(JNIEnv *env, jobject instance,
                                                          jbyteArray data_);

JNIEXPORT void JNICALL
Java_com_evenwell_grideye_Grideye_1NDK_initializeHumanDetect(JNIEnv *env, jobject instance);

JNIEXPORT void JNICALL
Java_com_evenwell_grideye_Grideye_1NDK_runHumanDetectionThresh(JNIEnv *env, jobject instance,
                                                               jfloat diffTemp_thresh,
                                                               jint labeling_thresh,
                                                               jint human_thresh,
                                                               jbyteArray data_);

JNIEXPORT void JNICALL
Java_com_evenwell_grideye_Grideye_1NDK_startHumanDetection(JNIEnv *env, jobject instance,
                                                           jshortArray jsDataArray);

JNIEXPORT void JNICALL
Java_com_evenwell_grideye_Grideye_1NDK_setDetectionConfig(JNIEnv *env, jobject instance,
                                                          jbyteArray jbDataArray);

JNIEXPORT void JNICALL
Java_com_evenwell_grideye_Grideye_1NDK_setJNIEnv(JNIEnv *env, jobject instance);


#ifdef __cplusplus
}
#endif
#endif
